name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version-file: 'go.mod'

      - run: go version

      - name: Build for Linux
        run: go build -o polic .
        env:
          GOOS: linux

      - name: Build for Windows
        run: go build -o polic.exe .
        env:
          GOOS: windows

      - name: Build for Mac
        run: go build -o polic-mac
        env:
          GOOS: darwin

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "polic*"
          token: ${{ github.token}}